In [1]:
import pandas as pd

In [4]:
url = "https://www.sectorspdr.com/sectorspdr/IDCO.Client.Spdrs.Index/Export/ExportCsv?symbol=xlf"
file = pd.read_csv(url, skiprows=1)
file.head()

,Symbol,Company Name,Index Weight,Last,Change,%Change,Volume,52 Week Range,Unnamed: 8
0,AFL,AFLAC Inc,0.92%,64.84,0.45,+0.70%,2.16 M,51.15 - 66.97,NaN
1,AIG,American Intl Group Inc,1.25%,63.79,1.02,+1.62%,3.80 M,44.54 - 64.90,NaN
2,AIZ,Assurant Inc,0.25%,185.42,3.59,+1.97%,426.51 K,141.78 - 185.58,NaN
3,ALL,Allstate Corp,0.92%,139.54,1.03,+0.74%,1.28 M,106.11 - 141.82,NaN
4,AMP,Ameriprise Financial Inc,0.78%,297.41,-2.95,-0.98%,609.39 K,234.72 - 332.37,NaN

In [5]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Symbol         67 non-null     object
 1   Company Name   67 non-null     object
 2   Index Weight   67 non-null     object
 3   Last           67 non-null     float64
 4   Change         67 non-null     float64
 5   %Change        67 non-null     object
 6   Volume         67 non-null     object
 7   52 Week Range  67 non-null     object
 8   Unnamed: 8     0 non-null      float64
dtypes: float64(3), object(6)
memory usage: 4.8+ KB

In [6]:
file.drop(labels = 'Unnamed: 8', axis = 1, inplace = True)
file.head(10)

,Symbol,Company Name,Index Weight,Last,Change,%Change,Volume,52 Week Range
0,AFL,AFLAC Inc,0.92%,64.84,0.45,+0.70%,2.16 M,51.15 - 66.97
1,AIG,American Intl Group Inc,1.25%,63.79,1.02,+1.62%,3.80 M,44.54 - 64.90
2,AIZ,Assurant Inc,0.25%,185.42,3.59,+1.97%,426.51 K,141.78 - 185.58
3,ALL,Allstate Corp,0.92%,139.54,1.03,+0.74%,1.28 M,106.11 - 141.82
4,AMP,Ameriprise Financial Inc,0.78%,297.41,-2.95,-0.98%,609.39 K,234.72 - 332.37
5,AON,Aon plc,1.66%,328.83,3.20,+0.98%,943.85 K,223.19 - 331.90
6,AXP,American Express Co,2.71%,187.17,0.17,+0.09%,2.65 M,140.68 - 199.55
7,BAC,Bank of America Corp,6.85%,40.90,-0.32,-0.78%,61.93 M,36.51 - 50.11
8,BEN,Franklin Resources Inc,0.19%,27.93,0.01,+0.04%,3.88 M,26.45 - 38.27
9,BK,The Bank of New York Mellon Corp,0.86%,49.45,-0.18,-0.36%,4.26 M,45.80 - 64.63

In [9]:
dir(file['Index Weight'].str)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__frozen',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_data',
 '_doc_args',
 '_freeze',
 '_get_series_list',
 '_index',
 '_inferred_dtype',
 '_is_categorical',
 '_is_string',
 '_name',
 '_orig',
 '_parent',
 '_validate',
 '_wrap_result',
 'capitalize',
 'casefold',
 'cat',
 'center',
 'contains',
 'count',
 'decode',
 'encode',
 'endswith',
 'extract',
 'extractall',
 'find',
 'findall',
 'fullmatch',
 'get',
 'get_dummies',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'islower',
 'isnumeric',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'len',
 'ljust',
 'lower',
 'lstrip',
 'match',
 'normalize',
 'pad',
 'partition',
 'repeat',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'slice',
 'slice_replace',
 'split',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'wrap',
 'zfill']

In [13]:
file['IW'] = file['Index Weight'].str.strip('%').apply(pd.to_numeric)
file

,Symbol,Company Name,Index Weight,Last,Change,%Change,Volume,52 Week Range,IW
0,AFL,AFLAC Inc,0.92%,64.84,0.45,+0.70%,2.16 M,51.15 - 66.97,0.92
1,AIG,American Intl Group Inc,1.25%,63.79,1.02,+1.62%,3.80 M,44.54 - 64.90,1.25
2,AIZ,Assurant Inc,0.25%,185.42,3.59,+1.97%,426.51 K,141.78 - 185.58,0.25
3,ALL,Allstate Corp,0.92%,139.54,1.03,+0.74%,1.28 M,106.11 - 141.82,0.92
4,AMP,Ameriprise Financial Inc,0.78%,297.41,-2.95,-0.98%,609.39 K,234.72 - 332.37,0.78
...,...,...,...,...,...,...,...,...,...
62,CBOE,"Cboe Global Markets, Inc",0.29%,116.85,2.43,+2.12%,533.45 K,98.80 - 139.00,0.29
63,BRO,Brown & Brown Inc,0.40%,72.56,0.29,+0.40%,1.79 M,46.46 - 74.00,0.40
64,FDS,FactSet Research System Inc,0.38%,429.12,-5.03,-1.16%,366.44 K,306.86 - 495.40,0.38
65,SBNY,Signature Bank NY,0.43%,289.82,-3.67,-1.25%,677.66 K,216.00 - 374.76,0.43
66,WTW,Willis Towers Watson PLC,0.68%,237.46,1.24,+0.52%,463.00 K,199.78 - 271.87,0.68

In [14]:
file.IW.sum()

99.99000000000001

In [15]:
file.IW.max()

15.19

In [16]:
file.IW.min()

0.19

In [17]:
file[file.IW == file.IW.max()]

,Symbol,Company Name,Index Weight,Last,Change,%Change,Volume,52 Week Range,IW
11,BRK.b,Berkshire Hathaway B,15.19%,351.88,-1.03,-0.29%,4.13 M,260.00 - 362.10,15.19

In [18]:
file[file.IW == file.IW.min()]

,Symbol,Company Name,Index Weight,Last,Change,%Change,Volume,52 Week Range,IW
8,BEN,Franklin Resources Inc,0.19%,27.93,0.01,+0.04%,3.88 M,26.45 - 38.27,0.19
24,IVZ,Invesco Ltd,0.19%,23.31,0.25,+1.08%,6.25 M,18.42 - 29.71,0.19

In [19]:
file['Company Name'].str.contains('Group')

0     False
1      True
2     False
3     False
4     False
      ...
62    False
63    False
64    False
65    False
66    False
Name: Company Name, Length: 67, dtype: bool

In [20]:
file['Company Name'].str.contains('Corp')

0     False
1     False
2     False
3      True
4     False
      ...
62    False
63    False
64    False
65    False
66    False
Name: Company Name, Length: 67, dtype: bool

In [21]:
file['Company Name'].str.contains('Group').count()

67

In [22]:
file['Company Name'].str.contains('Corp').count()

67

In [23]:
file['Symbol'][file['Company Name'].str.contains('Corp')].count()

16

In [25]:
file['Symbol'][file['Company Name'].str.contains('Corp|Group')].count()

26

In [26]:
file['Vol_lambda'] = file['Volume'].apply(lambda value: float(value.strip('K'))*1000 if 'K' in value else float(value.strip('M'))*1000000)

In [27]:
file.head()

,Symbol,Company Name,Index Weight,Last,Change,%Change,Volume,52 Week Range,IW,Vol_lambda
0,AFL,AFLAC Inc,0.92%,64.84,0.45,+0.70%,2.16 M,51.15 - 66.97,0.92,2160000.0
1,AIG,American Intl Group Inc,1.25%,63.79,1.02,+1.62%,3.80 M,44.54 - 64.90,1.25,3800000.0
2,AIZ,Assurant Inc,0.25%,185.42,3.59,+1.97%,426.51 K,141.78 - 185.58,0.25,426510.0
3,ALL,Allstate Corp,0.92%,139.54,1.03,+0.74%,1.28 M,106.11 - 141.82,0.92,1280000.0
4,AMP,Ameriprise Financial Inc,0.78%,297.41,-2.95,-0.98%,609.39 K,234.72 - 332.37,0.78,609390.0

In [28]:
file['52 Week Range'].str.split('-')

0       [51.15 ,  66.97]
1       [44.54 ,  64.90]
2     [141.78 ,  185.58]
3     [106.11 ,  141.82]
4     [234.72 ,  332.37]
             ...
62     [98.80 ,  139.00]
63      [46.46 ,  74.00]
64    [306.86 ,  495.40]
65    [216.00 ,  374.76]
66    [199.78 ,  271.87]
Name: 52 Week Range, Length: 67, dtype: object

In [30]:
file['Low'] = file['52 Week Range'].str.split('-').apply(lambda value: float(value[0]))
file.head()

,Symbol,Company Name,Index Weight,Last,Change,%Change,Volume,52 Week Range,IW,Vol_lambda,Low
0,AFL,AFLAC Inc,0.92%,64.84,0.45,+0.70%,2.16 M,51.15 - 66.97,0.92,2160000.0,51.15
1,AIG,American Intl Group Inc,1.25%,63.79,1.02,+1.62%,3.80 M,44.54 - 64.90,1.25,3800000.0,44.54
2,AIZ,Assurant Inc,0.25%,185.42,3.59,+1.97%,426.51 K,141.78 - 185.58,0.25,426510.0,141.78
3,ALL,Allstate Corp,0.92%,139.54,1.03,+0.74%,1.28 M,106.11 - 141.82,0.92,1280000.0,106.11
4,AMP,Ameriprise Financial Inc,0.78%,297.41,-2.95,-0.98%,609.39 K,234.72 - 332.37,0.78,609390.0,234.72

In [31]:
file['High'] = file['52 Week Range'].str.split('-').apply(lambda value: float(value[1]))
file.head()

,Symbol,Company Name,Index Weight,Last,Change,%Change,Volume,52 Week Range,IW,Vol_lambda,Low,High
0,AFL,AFLAC Inc,0.92%,64.84,0.45,+0.70%,2.16 M,51.15 - 66.97,0.92,2160000.0,51.15,66.97
1,AIG,American Intl Group Inc,1.25%,63.79,1.02,+1.62%,3.80 M,44.54 - 64.90,1.25,3800000.0,44.54,64.90
2,AIZ,Assurant Inc,0.25%,185.42,3.59,+1.97%,426.51 K,141.78 - 185.58,0.25,426510.0,141.78,185.58
3,ALL,Allstate Corp,0.92%,139.54,1.03,+0.74%,1.28 M,106.11 - 141.82,0.92,1280000.0,106.11,141.82
4,AMP,Ameriprise Financial Inc,0.78%,297.41,-2.95,-0.98%,609.39 K,234.72 - 332.37,0.78,609390.0,234.72,332.37

In [33]:
file['Diff'] = file['High'] - file['Low']
file.head()

,Symbol,Company Name,Index Weight,Last,Change,%Change,Volume,52 Week Range,IW,Vol_lambda,Low,High,Diff
0,AFL,AFLAC Inc,0.92%,64.84,0.45,+0.70%,2.16 M,51.15 - 66.97,0.92,2160000.0,51.15,66.97,15.82
1,AIG,American Intl Group Inc,1.25%,63.79,1.02,+1.62%,3.80 M,44.54 - 64.90,1.25,3800000.0,44.54,64.90,20.36
2,AIZ,Assurant Inc,0.25%,185.42,3.59,+1.97%,426.51 K,141.78 - 185.58,0.25,426510.0,141.78,185.58,43.80
3,ALL,Allstate Corp,0.92%,139.54,1.03,+0.74%,1.28 M,106.11 - 141.82,0.92,1280000.0,106.11,141.82,35.71
4,AMP,Ameriprise Financial Inc,0.78%,297.41,-2.95,-0.98%,609.39 K,234.72 - 332.37,0.78,609390.0,234.72,332.37,97.65